# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'scheduleinterface.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QGridLayout,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.NonModal)
        MainWindow.resize(1440, 900)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(60, 320, 1321, 541))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_2 = QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.lay6 = QHBoxLayout()
        self.lay6.setObjectName(u"lay6")
        self.mon6Edit = QTextEdit(self.frame)
        self.mon6Edit.setObjectName(u"mon6Edit")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mon6Edit.sizePolicy().hasHeightForWidth())
        self.mon6Edit.setSizePolicy(sizePolicy)
        font = QFont()
        font.setKerning(False)
        self.mon6Edit.setFont(font)
        self.mon6Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.mon6Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.mon6Edit.setLineWidth(24)
        self.mon6Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.mon6Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.mon6Edit.setReadOnly(True)

        self.lay6.addWidget(self.mon6Edit)

        self.tue6Edit = QTextEdit(self.frame)
        self.tue6Edit.setObjectName(u"tue6Edit")
        sizePolicy.setHeightForWidth(self.tue6Edit.sizePolicy().hasHeightForWidth())
        self.tue6Edit.setSizePolicy(sizePolicy)
        self.tue6Edit.setFont(font)
        self.tue6Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.tue6Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.tue6Edit.setLineWidth(24)
        self.tue6Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.tue6Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.tue6Edit.setReadOnly(True)

        self.lay6.addWidget(self.tue6Edit)

        self.wed6Edit = QTextEdit(self.frame)
        self.wed6Edit.setObjectName(u"wed6Edit")
        sizePolicy.setHeightForWidth(self.wed6Edit.sizePolicy().hasHeightForWidth())
        self.wed6Edit.setSizePolicy(sizePolicy)
        self.wed6Edit.setFont(font)
        self.wed6Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.wed6Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.wed6Edit.setLineWidth(24)
        self.wed6Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.wed6Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.wed6Edit.setReadOnly(True)

        self.lay6.addWidget(self.wed6Edit)

        self.thr6Edit = QTextEdit(self.frame)
        self.thr6Edit.setObjectName(u"thr6Edit")
        sizePolicy.setHeightForWidth(self.thr6Edit.sizePolicy().hasHeightForWidth())
        self.thr6Edit.setSizePolicy(sizePolicy)
        self.thr6Edit.setFont(font)
        self.thr6Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.thr6Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.thr6Edit.setLineWidth(24)
        self.thr6Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.thr6Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.thr6Edit.setReadOnly(True)

        self.lay6.addWidget(self.thr6Edit)

        self.fri6Edit = QTextEdit(self.frame)
        self.fri6Edit.setObjectName(u"fri6Edit")
        sizePolicy.setHeightForWidth(self.fri6Edit.sizePolicy().hasHeightForWidth())
        self.fri6Edit.setSizePolicy(sizePolicy)
        self.fri6Edit.setFont(font)
        self.fri6Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.fri6Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.fri6Edit.setLineWidth(24)
        self.fri6Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.fri6Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.fri6Edit.setReadOnly(True)

        self.lay6.addWidget(self.fri6Edit)

        self.sat6Edit = QTextEdit(self.frame)
        self.sat6Edit.setObjectName(u"sat6Edit")
        sizePolicy.setHeightForWidth(self.sat6Edit.sizePolicy().hasHeightForWidth())
        self.sat6Edit.setSizePolicy(sizePolicy)
        self.sat6Edit.setFont(font)
        self.sat6Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sat6Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sat6Edit.setLineWidth(24)
        self.sat6Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sat6Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sat6Edit.setReadOnly(True)

        self.lay6.addWidget(self.sat6Edit)

        self.sun6Edit = QTextEdit(self.frame)
        self.sun6Edit.setObjectName(u"sun6Edit")
        sizePolicy.setHeightForWidth(self.sun6Edit.sizePolicy().hasHeightForWidth())
        self.sun6Edit.setSizePolicy(sizePolicy)
        self.sun6Edit.setFont(font)
        self.sun6Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sun6Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sun6Edit.setLineWidth(24)
        self.sun6Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sun6Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sun6Edit.setReadOnly(True)

        self.lay6.addWidget(self.sun6Edit)


        self.gridLayout_2.addLayout(self.lay6, 5, 0, 1, 1)

        self.lay5 = QHBoxLayout()
        self.lay5.setObjectName(u"lay5")
        self.mon5Edit = QTextEdit(self.frame)
        self.mon5Edit.setObjectName(u"mon5Edit")
        sizePolicy.setHeightForWidth(self.mon5Edit.sizePolicy().hasHeightForWidth())
        self.mon5Edit.setSizePolicy(sizePolicy)
        self.mon5Edit.setFont(font)
        self.mon5Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.mon5Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.mon5Edit.setLineWidth(24)
        self.mon5Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.mon5Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.mon5Edit.setReadOnly(True)

        self.lay5.addWidget(self.mon5Edit)

        self.tue5Edit = QTextEdit(self.frame)
        self.tue5Edit.setObjectName(u"tue5Edit")
        sizePolicy.setHeightForWidth(self.tue5Edit.sizePolicy().hasHeightForWidth())
        self.tue5Edit.setSizePolicy(sizePolicy)
        self.tue5Edit.setFont(font)
        self.tue5Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.tue5Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.tue5Edit.setLineWidth(24)
        self.tue5Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.tue5Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.tue5Edit.setReadOnly(True)

        self.lay5.addWidget(self.tue5Edit)

        self.wed5Edit = QTextEdit(self.frame)
        self.wed5Edit.setObjectName(u"wed5Edit")
        sizePolicy.setHeightForWidth(self.wed5Edit.sizePolicy().hasHeightForWidth())
        self.wed5Edit.setSizePolicy(sizePolicy)
        self.wed5Edit.setFont(font)
        self.wed5Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.wed5Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.wed5Edit.setLineWidth(24)
        self.wed5Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.wed5Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.wed5Edit.setReadOnly(True)

        self.lay5.addWidget(self.wed5Edit)

        self.thr5Edit = QTextEdit(self.frame)
        self.thr5Edit.setObjectName(u"thr5Edit")
        sizePolicy.setHeightForWidth(self.thr5Edit.sizePolicy().hasHeightForWidth())
        self.thr5Edit.setSizePolicy(sizePolicy)
        self.thr5Edit.setFont(font)
        self.thr5Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.thr5Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.thr5Edit.setLineWidth(24)
        self.thr5Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.thr5Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.thr5Edit.setReadOnly(True)

        self.lay5.addWidget(self.thr5Edit)

        self.fri5Edit = QTextEdit(self.frame)
        self.fri5Edit.setObjectName(u"fri5Edit")
        sizePolicy.setHeightForWidth(self.fri5Edit.sizePolicy().hasHeightForWidth())
        self.fri5Edit.setSizePolicy(sizePolicy)
        self.fri5Edit.setFont(font)
        self.fri5Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.fri5Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.fri5Edit.setLineWidth(24)
        self.fri5Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.fri5Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.fri5Edit.setReadOnly(True)

        self.lay5.addWidget(self.fri5Edit)

        self.sat5Edit = QTextEdit(self.frame)
        self.sat5Edit.setObjectName(u"sat5Edit")
        sizePolicy.setHeightForWidth(self.sat5Edit.sizePolicy().hasHeightForWidth())
        self.sat5Edit.setSizePolicy(sizePolicy)
        self.sat5Edit.setFont(font)
        self.sat5Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sat5Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sat5Edit.setLineWidth(24)
        self.sat5Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sat5Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sat5Edit.setReadOnly(True)

        self.lay5.addWidget(self.sat5Edit)

        self.sun5Edit = QTextEdit(self.frame)
        self.sun5Edit.setObjectName(u"sun5Edit")
        sizePolicy.setHeightForWidth(self.sun5Edit.sizePolicy().hasHeightForWidth())
        self.sun5Edit.setSizePolicy(sizePolicy)
        self.sun5Edit.setFont(font)
        self.sun5Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sun5Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sun5Edit.setLineWidth(24)
        self.sun5Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sun5Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sun5Edit.setReadOnly(True)

        self.lay5.addWidget(self.sun5Edit)


        self.gridLayout_2.addLayout(self.lay5, 4, 0, 1, 1)

        self.lay4 = QHBoxLayout()
        self.lay4.setObjectName(u"lay4")
        self.mon4Edit = QTextEdit(self.frame)
        self.mon4Edit.setObjectName(u"mon4Edit")
        sizePolicy.setHeightForWidth(self.mon4Edit.sizePolicy().hasHeightForWidth())
        self.mon4Edit.setSizePolicy(sizePolicy)
        self.mon4Edit.setFont(font)
        self.mon4Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.mon4Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.mon4Edit.setLineWidth(24)
        self.mon4Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.mon4Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.mon4Edit.setReadOnly(True)

        self.lay4.addWidget(self.mon4Edit)

        self.tue4Edit = QTextEdit(self.frame)
        self.tue4Edit.setObjectName(u"tue4Edit")
        sizePolicy.setHeightForWidth(self.tue4Edit.sizePolicy().hasHeightForWidth())
        self.tue4Edit.setSizePolicy(sizePolicy)
        self.tue4Edit.setFont(font)
        self.tue4Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.tue4Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.tue4Edit.setLineWidth(24)
        self.tue4Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.tue4Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.tue4Edit.setReadOnly(True)

        self.lay4.addWidget(self.tue4Edit)

        self.wed4Edit = QTextEdit(self.frame)
        self.wed4Edit.setObjectName(u"wed4Edit")
        sizePolicy.setHeightForWidth(self.wed4Edit.sizePolicy().hasHeightForWidth())
        self.wed4Edit.setSizePolicy(sizePolicy)
        self.wed4Edit.setFont(font)
        self.wed4Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.wed4Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.wed4Edit.setLineWidth(24)
        self.wed4Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.wed4Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.wed4Edit.setReadOnly(True)

        self.lay4.addWidget(self.wed4Edit)

        self.thr4Edit = QTextEdit(self.frame)
        self.thr4Edit.setObjectName(u"thr4Edit")
        sizePolicy.setHeightForWidth(self.thr4Edit.sizePolicy().hasHeightForWidth())
        self.thr4Edit.setSizePolicy(sizePolicy)
        self.thr4Edit.setFont(font)
        self.thr4Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.thr4Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.thr4Edit.setLineWidth(24)
        self.thr4Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.thr4Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.thr4Edit.setReadOnly(True)

        self.lay4.addWidget(self.thr4Edit)

        self.fri4Edit = QTextEdit(self.frame)
        self.fri4Edit.setObjectName(u"fri4Edit")
        sizePolicy.setHeightForWidth(self.fri4Edit.sizePolicy().hasHeightForWidth())
        self.fri4Edit.setSizePolicy(sizePolicy)
        self.fri4Edit.setFont(font)
        self.fri4Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.fri4Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.fri4Edit.setLineWidth(24)
        self.fri4Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.fri4Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.fri4Edit.setReadOnly(True)

        self.lay4.addWidget(self.fri4Edit)

        self.sat4Edit = QTextEdit(self.frame)
        self.sat4Edit.setObjectName(u"sat4Edit")
        sizePolicy.setHeightForWidth(self.sat4Edit.sizePolicy().hasHeightForWidth())
        self.sat4Edit.setSizePolicy(sizePolicy)
        self.sat4Edit.setFont(font)
        self.sat4Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sat4Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sat4Edit.setLineWidth(24)
        self.sat4Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sat4Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sat4Edit.setReadOnly(True)

        self.lay4.addWidget(self.sat4Edit)

        self.sun4Edit = QTextEdit(self.frame)
        self.sun4Edit.setObjectName(u"sun4Edit")
        sizePolicy.setHeightForWidth(self.sun4Edit.sizePolicy().hasHeightForWidth())
        self.sun4Edit.setSizePolicy(sizePolicy)
        self.sun4Edit.setFont(font)
        self.sun4Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sun4Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sun4Edit.setLineWidth(24)
        self.sun4Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sun4Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sun4Edit.setReadOnly(True)

        self.lay4.addWidget(self.sun4Edit)


        self.gridLayout_2.addLayout(self.lay4, 3, 0, 1, 1)

        self.lay2 = QHBoxLayout()
        self.lay2.setObjectName(u"lay2")
        self.mon2Edit = QTextEdit(self.frame)
        self.mon2Edit.setObjectName(u"mon2Edit")
        sizePolicy.setHeightForWidth(self.mon2Edit.sizePolicy().hasHeightForWidth())
        self.mon2Edit.setSizePolicy(sizePolicy)
        self.mon2Edit.setFont(font)
        self.mon2Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.mon2Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.mon2Edit.setLineWidth(24)
        self.mon2Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.mon2Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.mon2Edit.setReadOnly(True)

        self.lay2.addWidget(self.mon2Edit)

        self.tue2Edit = QTextEdit(self.frame)
        self.tue2Edit.setObjectName(u"tue2Edit")
        sizePolicy.setHeightForWidth(self.tue2Edit.sizePolicy().hasHeightForWidth())
        self.tue2Edit.setSizePolicy(sizePolicy)
        self.tue2Edit.setFont(font)
        self.tue2Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.tue2Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.tue2Edit.setLineWidth(24)
        self.tue2Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.tue2Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.tue2Edit.setReadOnly(True)

        self.lay2.addWidget(self.tue2Edit)

        self.wed2Edit = QTextEdit(self.frame)
        self.wed2Edit.setObjectName(u"wed2Edit")
        sizePolicy.setHeightForWidth(self.wed2Edit.sizePolicy().hasHeightForWidth())
        self.wed2Edit.setSizePolicy(sizePolicy)
        self.wed2Edit.setFont(font)
        self.wed2Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.wed2Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.wed2Edit.setLineWidth(24)
        self.wed2Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.wed2Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.wed2Edit.setReadOnly(True)

        self.lay2.addWidget(self.wed2Edit)

        self.thr2Edit = QTextEdit(self.frame)
        self.thr2Edit.setObjectName(u"thr2Edit")
        sizePolicy.setHeightForWidth(self.thr2Edit.sizePolicy().hasHeightForWidth())
        self.thr2Edit.setSizePolicy(sizePolicy)
        self.thr2Edit.setFont(font)
        self.thr2Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.thr2Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.thr2Edit.setLineWidth(24)
        self.thr2Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.thr2Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.thr2Edit.setReadOnly(True)

        self.lay2.addWidget(self.thr2Edit)

        self.fri2Edit = QTextEdit(self.frame)
        self.fri2Edit.setObjectName(u"fri2Edit")
        sizePolicy.setHeightForWidth(self.fri2Edit.sizePolicy().hasHeightForWidth())
        self.fri2Edit.setSizePolicy(sizePolicy)
        self.fri2Edit.setFont(font)
        self.fri2Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.fri2Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.fri2Edit.setLineWidth(24)
        self.fri2Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.fri2Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.fri2Edit.setReadOnly(True)

        self.lay2.addWidget(self.fri2Edit)

        self.sat2Edit = QTextEdit(self.frame)
        self.sat2Edit.setObjectName(u"sat2Edit")
        sizePolicy.setHeightForWidth(self.sat2Edit.sizePolicy().hasHeightForWidth())
        self.sat2Edit.setSizePolicy(sizePolicy)
        self.sat2Edit.setFont(font)
        self.sat2Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sat2Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sat2Edit.setLineWidth(24)
        self.sat2Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sat2Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sat2Edit.setReadOnly(True)

        self.lay2.addWidget(self.sat2Edit)

        self.sun2Edit = QTextEdit(self.frame)
        self.sun2Edit.setObjectName(u"sun2Edit")
        sizePolicy.setHeightForWidth(self.sun2Edit.sizePolicy().hasHeightForWidth())
        self.sun2Edit.setSizePolicy(sizePolicy)
        self.sun2Edit.setFont(font)
        self.sun2Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sun2Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sun2Edit.setLineWidth(24)
        self.sun2Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sun2Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sun2Edit.setReadOnly(True)

        self.lay2.addWidget(self.sun2Edit)


        self.gridLayout_2.addLayout(self.lay2, 1, 0, 1, 1)

        self.lay3 = QHBoxLayout()
        self.lay3.setObjectName(u"lay3")
        self.mon3Edit = QTextEdit(self.frame)
        self.mon3Edit.setObjectName(u"mon3Edit")
        sizePolicy.setHeightForWidth(self.mon3Edit.sizePolicy().hasHeightForWidth())
        self.mon3Edit.setSizePolicy(sizePolicy)
        self.mon3Edit.setFont(font)
        self.mon3Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.mon3Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.mon3Edit.setLineWidth(24)
        self.mon3Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.mon3Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.mon3Edit.setReadOnly(True)

        self.lay3.addWidget(self.mon3Edit)

        self.tue3Edit = QTextEdit(self.frame)
        self.tue3Edit.setObjectName(u"tue3Edit")
        sizePolicy.setHeightForWidth(self.tue3Edit.sizePolicy().hasHeightForWidth())
        self.tue3Edit.setSizePolicy(sizePolicy)
        self.tue3Edit.setFont(font)
        self.tue3Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.tue3Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.tue3Edit.setLineWidth(24)
        self.tue3Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.tue3Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.tue3Edit.setReadOnly(True)

        self.lay3.addWidget(self.tue3Edit)

        self.wed3Edit = QTextEdit(self.frame)
        self.wed3Edit.setObjectName(u"wed3Edit")
        sizePolicy.setHeightForWidth(self.wed3Edit.sizePolicy().hasHeightForWidth())
        self.wed3Edit.setSizePolicy(sizePolicy)
        self.wed3Edit.setFont(font)
        self.wed3Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.wed3Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.wed3Edit.setLineWidth(24)
        self.wed3Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.wed3Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.wed3Edit.setReadOnly(True)

        self.lay3.addWidget(self.wed3Edit)

        self.thr3Edit = QTextEdit(self.frame)
        self.thr3Edit.setObjectName(u"thr3Edit")
        sizePolicy.setHeightForWidth(self.thr3Edit.sizePolicy().hasHeightForWidth())
        self.thr3Edit.setSizePolicy(sizePolicy)
        self.thr3Edit.setFont(font)
        self.thr3Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.thr3Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.thr3Edit.setLineWidth(24)
        self.thr3Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.thr3Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.thr3Edit.setReadOnly(True)

        self.lay3.addWidget(self.thr3Edit)

        self.fri3Edit = QTextEdit(self.frame)
        self.fri3Edit.setObjectName(u"fri3Edit")
        sizePolicy.setHeightForWidth(self.fri3Edit.sizePolicy().hasHeightForWidth())
        self.fri3Edit.setSizePolicy(sizePolicy)
        self.fri3Edit.setFont(font)
        self.fri3Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.fri3Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.fri3Edit.setLineWidth(24)
        self.fri3Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.fri3Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.fri3Edit.setReadOnly(True)

        self.lay3.addWidget(self.fri3Edit)

        self.sat3Edit = QTextEdit(self.frame)
        self.sat3Edit.setObjectName(u"sat3Edit")
        sizePolicy.setHeightForWidth(self.sat3Edit.sizePolicy().hasHeightForWidth())
        self.sat3Edit.setSizePolicy(sizePolicy)
        self.sat3Edit.setFont(font)
        self.sat3Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sat3Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sat3Edit.setLineWidth(24)
        self.sat3Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sat3Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sat3Edit.setReadOnly(True)

        self.lay3.addWidget(self.sat3Edit)

        self.sun3Edit = QTextEdit(self.frame)
        self.sun3Edit.setObjectName(u"sun3Edit")
        sizePolicy.setHeightForWidth(self.sun3Edit.sizePolicy().hasHeightForWidth())
        self.sun3Edit.setSizePolicy(sizePolicy)
        self.sun3Edit.setFont(font)
        self.sun3Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sun3Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sun3Edit.setLineWidth(24)
        self.sun3Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sun3Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sun3Edit.setReadOnly(True)

        self.lay3.addWidget(self.sun3Edit)


        self.gridLayout_2.addLayout(self.lay3, 2, 0, 1, 1)

        self.lay1 = QHBoxLayout()
        self.lay1.setObjectName(u"lay1")
        self.mon1Edit = QTextEdit(self.frame)
        self.mon1Edit.setObjectName(u"mon1Edit")
        sizePolicy.setHeightForWidth(self.mon1Edit.sizePolicy().hasHeightForWidth())
        self.mon1Edit.setSizePolicy(sizePolicy)
        self.mon1Edit.setFont(font)
        self.mon1Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.mon1Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.mon1Edit.setLineWidth(24)
        self.mon1Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.mon1Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.mon1Edit.setReadOnly(True)

        self.lay1.addWidget(self.mon1Edit)

        self.tue1Edit = QTextEdit(self.frame)
        self.tue1Edit.setObjectName(u"tue1Edit")
        sizePolicy.setHeightForWidth(self.tue1Edit.sizePolicy().hasHeightForWidth())
        self.tue1Edit.setSizePolicy(sizePolicy)
        self.tue1Edit.setFont(font)
        self.tue1Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.tue1Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.tue1Edit.setLineWidth(24)
        self.tue1Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.tue1Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.tue1Edit.setReadOnly(True)

        self.lay1.addWidget(self.tue1Edit)

        self.wed1Edit = QTextEdit(self.frame)
        self.wed1Edit.setObjectName(u"wed1Edit")
        sizePolicy.setHeightForWidth(self.wed1Edit.sizePolicy().hasHeightForWidth())
        self.wed1Edit.setSizePolicy(sizePolicy)
        self.wed1Edit.setFont(font)
        self.wed1Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.wed1Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.wed1Edit.setLineWidth(24)
        self.wed1Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.wed1Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.wed1Edit.setReadOnly(True)

        self.lay1.addWidget(self.wed1Edit)

        self.thr1Edit = QTextEdit(self.frame)
        self.thr1Edit.setObjectName(u"thr1Edit")
        sizePolicy.setHeightForWidth(self.thr1Edit.sizePolicy().hasHeightForWidth())
        self.thr1Edit.setSizePolicy(sizePolicy)
        self.thr1Edit.setFont(font)
        self.thr1Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.thr1Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.thr1Edit.setLineWidth(24)
        self.thr1Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.thr1Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.thr1Edit.setReadOnly(True)

        self.lay1.addWidget(self.thr1Edit)

        self.fri1Edit = QTextEdit(self.frame)
        self.fri1Edit.setObjectName(u"fri1Edit")
        sizePolicy.setHeightForWidth(self.fri1Edit.sizePolicy().hasHeightForWidth())
        self.fri1Edit.setSizePolicy(sizePolicy)
        self.fri1Edit.setFont(font)
        self.fri1Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.fri1Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.fri1Edit.setLineWidth(24)
        self.fri1Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.fri1Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.fri1Edit.setReadOnly(True)

        self.lay1.addWidget(self.fri1Edit)

        self.sat1Edit = QTextEdit(self.frame)
        self.sat1Edit.setObjectName(u"sat1Edit")
        sizePolicy.setHeightForWidth(self.sat1Edit.sizePolicy().hasHeightForWidth())
        self.sat1Edit.setSizePolicy(sizePolicy)
        self.sat1Edit.setFont(font)
        self.sat1Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sat1Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sat1Edit.setLineWidth(24)
        self.sat1Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sat1Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sat1Edit.setReadOnly(True)

        self.lay1.addWidget(self.sat1Edit)

        self.sun1Edit = QTextEdit(self.frame)
        self.sun1Edit.setObjectName(u"sun1Edit")
        sizePolicy.setHeightForWidth(self.sun1Edit.sizePolicy().hasHeightForWidth())
        self.sun1Edit.setSizePolicy(sizePolicy)
        self.sun1Edit.setFont(font)
        self.sun1Edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.sun1Edit.setFrameShape(QFrame.Shape.StyledPanel)
        self.sun1Edit.setLineWidth(24)
        self.sun1Edit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sun1Edit.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.sun1Edit.setReadOnly(True)

        self.lay1.addWidget(self.sun1Edit)


        self.gridLayout_2.addLayout(self.lay1, 0, 0, 1, 1)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(120, 30, 1191, 131))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout = QGridLayout(self.frame_2)
        self.gridLayout.setObjectName(u"gridLayout")
        self.timeButton = QPushButton(self.frame_2)
        self.timeButton.setObjectName(u"timeButton")
        sizePolicy.setHeightForWidth(self.timeButton.sizePolicy().hasHeightForWidth())
        self.timeButton.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.timeButton, 0, 0, 1, 1)

        self.weekButton = QPushButton(self.frame_2)
        self.weekButton.setObjectName(u"weekButton")
        sizePolicy.setHeightForWidth(self.weekButton.sizePolicy().hasHeightForWidth())
        self.weekButton.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.weekButton, 0, 1, 1, 1)

        self.subjButton = QPushButton(self.frame_2)
        self.subjButton.setObjectName(u"subjButton")
        sizePolicy.setHeightForWidth(self.subjButton.sizePolicy().hasHeightForWidth())
        self.subjButton.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.subjButton, 0, 2, 1, 1)

        self.typelessonButton = QPushButton(self.frame_2)
        self.typelessonButton.setObjectName(u"typelessonButton")
        sizePolicy.setHeightForWidth(self.typelessonButton.sizePolicy().hasHeightForWidth())
        self.typelessonButton.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.typelessonButton, 1, 0, 1, 1)

        self.teacherButton = QPushButton(self.frame_2)
        self.teacherButton.setObjectName(u"teacherButton")
        sizePolicy.setHeightForWidth(self.teacherButton.sizePolicy().hasHeightForWidth())
        self.teacherButton.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.teacherButton, 1, 1, 1, 1)

        self.roomButton = QPushButton(self.frame_2)
        self.roomButton.setObjectName(u"roomButton")
        sizePolicy.setHeightForWidth(self.roomButton.sizePolicy().hasHeightForWidth())
        self.roomButton.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.roomButton, 1, 2, 1, 1)

        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(230, 170, 931, 61))
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(140, 260, 1301, 73))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")
        font1 = QFont()
        font1.setPointSize(18)
        font1.setBold(True)
        self.label.setFont(font1)

        self.horizontalLayout.addWidget(self.label)

        self.label_2 = QLabel(self.layoutWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font1)

        self.horizontalLayout.addWidget(self.label_2)

        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font1)

        self.horizontalLayout.addWidget(self.label_4)

        self.label_3 = QLabel(self.layoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font1)

        self.horizontalLayout.addWidget(self.label_3)

        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setFont(font1)

        self.horizontalLayout.addWidget(self.label_5)

        self.label_6 = QLabel(self.layoutWidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font1)

        self.horizontalLayout.addWidget(self.label_6)

        self.label_7 = QLabel(self.layoutWidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFont(font1)

        self.horizontalLayout.addWidget(self.label_7)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1440, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.timeButton.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0420\u0415\u041c\u042f", None))
        self.weekButton.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0415\u0414\u0415\u041b\u042f (\u0427\u0401\u0422/\u041d\u0415\u0427\u0401\u0422)", None))
        self.subjButton.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0420\u0415\u0414\u041c\u0415\u0422", None))
        self.typelessonButton.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0418\u041f \u0417\u0410\u041d\u042f\u0422\u0418\u0419 (\u041b\u0415\u041a\u0426\u0418\u042f/\u041f\u0420\u0410\u041a\u0422\u0418\u041a\u0410)", None))
        self.teacherButton.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0420\u0415\u041f\u041e\u0414\u0410\u0412\u0410\u0422\u0415\u041b\u042c", None))
        self.roomButton.setText(QCoreApplication.translate("MainWindow", u"\u0410\u0423\u0414\u0418\u0422\u041e\u0420\u0418\u042f", None))
        self.lineEdit.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u041f\u041d", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0422", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0420", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u0427\u0422", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0422", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0411", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0421", None))
    # retranslateUi

